
services:
  cosiap_frontend:
    #restart: always
    stdin_open: true
    container_name: cosiap_frontend-1
    build:
      context: .
    volumes: 
      - .:/app
      #- /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"